version: "3.5"

services:
  catalog_service:
    build:
      context: ../
      dockerfile: src/CatalogService/BevShopping.Catalog.Api/Dockerfile
    restart: unless-stopped
    ports:
      - "5010-5011:5010"
    networks:
      - network-microservice
    links:
      - db-catalog
      - consul
    depends_on:
      - db-catalog
      - consul
